#  Name of workflow
name: Deploy workflow

# When workflow is triggered
on:
 push:
  branches: [master]

# Jobs to carry out
jobs:
 deploy:
  # Operating system to run job on
  runs-on: ubuntu-latest
  # Steps in job
  steps:
   # Get code from repo
   - name: Checkout code
     uses: actions/checkout@v2
   # Install NodeJS
   - name: Use Node.js 12
     uses: actions/setup-node@v2
     with:
      node-version: '12'
   # Run npm install and build on our code
   - name: Build React static files
     run: |
      npm install
      npm run build --if-present
   # Deploy to Netlify using our production secrets
   - name: Deploy to netlify
     uses: netlify/actions/cli@master
     env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
     with:
      args: deploy --dir=build --prod
